apiVersion: "v1"
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  containers:
    - name: web
      image: us.icr.io/mayanksachan/webapp
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
